--- 
title: "Data Package Best Practices"
author: "Environmental Data Initiative"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
# bibliography: [book.bib, packages.bib]
biblio-style: apalike
# link-citations: yes
description: "Best practice recommendations for data packages, described by Ecological Metadata Language (EML)."
---

## Overview {-}
This website contains current “Best Practice” recommendations for ecological and environmental science data packages. These recommendations are directed towards the following goals:

- Provide guidance and clarification in the use of Ecological Metadata Language (EML)
- Minimize heterogeneity of EML documents to simplify development and re-use of software built to ingest it
- Maximize interoperability of EML documents to facilitate data synthesis


## Metadata concepts {-}
These recommendations apply to most or all scientific domains. This section subsumes V3 of the static document "Best Practices for Dataset Metadata in Ecological Metadata Language (EML)"

 **[Best Practices for Dataset Metadata in Ecological Metadata Language (EML)](EMLmetadata/index.html)**
  
## Scientific domains {-}
many of these topics have extensive, related code bases, which some of these recommendations take into account (and link to). Such as

- community survey data
- meteorology/hydrology data
- genomics and metagenomics
  
**[Recommendations for data from specific Scientific domains{(science_domain/index.html)}**
  
## Challenging data types {-}
Certain data have special handling based on their acquisition method or platform. Some are raw data that should be preserved because they have uses beyond their original purpose. Many are not specific to any one scientific domain. **how about a better title for these!?** Examples:

- offline data 
  - sometimes necessary if size prevents efficient delivery over HTTP
- key-value pair tables 
  - and the choice of long vs. wide
- model output
- drone-collected
- photo imagery
- acoustics

**LINK TO BPs about Challenging data types**


